name: ulusal Kanallar Botu Guncelle

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Bu satır ÇOK ÖNEMLİ
    
    steps:
      - name: Depoyu cek
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests beautifulsoup4

      - name: Botu Calistir
        run: python ulu.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add ulu.m3u
          git diff --staged --quiet || git commit -m "Ulusal ve Spor Listesi Guncellendi: $(date)"
          git push
