name: Sporcafe Bot Guncelle

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Bu önemli!
      
    steps:
      - name: Depoyu cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Botu Calistir
        run: python main.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          # Token'ı kullanarak remote URL'i güncelle
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          if [ -f Sporcafe.m3u ]; then
            git add Sporcafe.m3u
            git commit -m "Sporcafe Liste Guncellendi: $(date)" || echo "Değişiklik yok"
            git push
          else
            echo "Dosya olusmadigi icin yukleme yapilamadi."
          fi
